import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const generalSans = localFont({
  src: [
    {
      path: '../public/fonts/GeneralSans-Regular.otf',
      weight: '500',
      style: 'normal'
    }
  ],
  variable: '--font-general-sans',
})

const druk = localFont({
  src: [
    {
      path: '../public/fonts/Druk-MediumItalic-Trial.otf',
      weight: '500',
      style: 'italic'
    }
  ],
  variable: '--font-druk',
})


export const metadata: Metadata = {
  title: "Landing Page Reveal Animation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${generalSans.variable} ${druk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
